<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>WIO-fish - Appendix D — Weight-Length Relationships</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./basicstats.html" rel="next">
<link href="./installPackages.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Appendix D — Weight-Length Relationships</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./" class="sidebar-logo-link">
      <img src="./FAO_logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">WIO-fish</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lugoga/ecasData" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rstudio.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting Started with R and RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Rlanguage.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R as a Programming Language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Packages</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Entry and Management</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./loadingData.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Loading Data and Data Cleaning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sample.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sample Data in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicFishStats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic Fisheries Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicFishPlotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Plotting Fisheries Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulate Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R language installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installRstudio.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">What is RStudio?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installPackages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Install packages in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lw.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Weight-Length Relationships</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicstats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title"><strong>Basic Data Manipulations</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recruitment.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Recruitment and logistic model</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#required-packages-for-this-supplement" id="toc-required-packages-for-this-supplement" class="nav-link active" data-scroll-target="#required-packages-for-this-supplement"> <span class="header-section-number">D.1</span> Required Packages for this Supplement</a></li>
  <li><a href="#data-used-in-this-supplement" id="toc-data-used-in-this-supplement" class="nav-link" data-scroll-target="#data-used-in-this-supplement"> <span class="header-section-number">D.2</span> Data Used in this Supplement</a></li>
  <li><a href="#full-model" id="toc-full-model" class="nav-link" data-scroll-target="#full-model"> <span class="header-section-number">D.3</span> Full Model</a></li>
  <li><a href="#pinpointing-specific-differences-among-slopes" id="toc-pinpointing-specific-differences-among-slopes" class="nav-link" data-scroll-target="#pinpointing-specific-differences-among-slopes"> <span class="header-section-number">D.4</span> <strong>Pinpointing Specific Differences Among Slopes</strong></a></li>
  <li><a href="#a-summary-plot" id="toc-a-summary-plot" class="nav-link" data-scroll-target="#a-summary-plot"> <span class="header-section-number">D.5</span> A Summary Plot</a></li>
  <li><a href="#pinpointing-specific-differences-among-intercepts" id="toc-pinpointing-specific-differences-among-intercepts" class="nav-link" data-scroll-target="#pinpointing-specific-differences-among-intercepts"> <span class="header-section-number">D.6</span> Pinpointing Specific Differences Among Intercepts</a></li>
  <li><a href="#reproducibility-information" id="toc-reproducibility-information" class="nav-link" data-scroll-target="#reproducibility-information"> <span class="header-section-number">D.7</span> Reproducibility Information</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"> <span class="header-section-number">D.8</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Appendix D — Weight-Length Relationships</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>DVR with More than Two Groups</p>
<ul>
<li><p><a href="http://derekogle.com/IFAR/supplements/weightlength/index.html#full-model">Full Model</a></p></li>
<li><p><a href="http://derekogle.com/IFAR/supplements/weightlength/index.html#pinpointing-specific-differences-among-slopes">Pinpointing Specific Differences Among Slopes</a></p></li>
<li><p><a href="http://derekogle.com/IFAR/supplements/weightlength/index.html#a-summary-plot">A Summary Plot</a></p></li>
<li><p><a href="http://derekogle.com/IFAR/supplements/weightlength/index.html#pinpointing-specific-differences-among-intercepts">Pinpointing Specific Differences Among Intercepts</a></p></li>
</ul>
<p>Dummy variable regression (DVR) was introduced in Chapter 7 of <a href="http://derekogle.com/IFAR/"><em>Introductory Fisheries Analyses with R</em></a> in the context of determining if the slope and y-intercept parameters of weight-length relationship regressions differed between fish captured in two different years. That analysis may be extended to more than two groups, though more dummy variables are required and special methods are needed to determine which pairs of groups (if any) differ. This supplement demonstrates how to extend the DVR to more than two groups.</p>
<section id="required-packages-for-this-supplement" class="level2" data-number="D.1">
<h2 data-number="D.1" class="anchored" data-anchor-id="required-packages-for-this-supplement"><span class="header-section-number">D.1</span> Required Packages for this Supplement</h2>
<p>Functions used in this supplement require the packages shown below.</p>
<pre><code>&gt; library(FSA)
&gt; library(dplyr)
&gt; library(car)</code></pre>
</section>
<section id="data-used-in-this-supplement" class="level2" data-number="D.2">
<h2 data-number="D.2" class="anchored" data-anchor-id="data-used-in-this-supplement"><span class="header-section-number">D.2</span> Data Used in this Supplement</h2>
<p>Weights (g) and total lengths (mm) from Ruffe (<em>Gymnocephalus cernuus</em>) captured in the St.Louis River Harbor (Minnesota and Wisconsin) were used in Chapter 7 of <strong>IFAR</strong> and will also be used in this supplement. These data are from Ogle and Winfield (2009) and are in <code>RuffeSLRH.csv</code> ( <a href="http://derekogle.com/IFAR/scripts/RuffeSLRH.csv">download</a>). To eliminate within-season variability, only Ruffe captured in July are used here. Additionally, a factored version of <code>year</code> was created, the common logarithms of weight and length were created, and the <code>fishID</code>, <code>month</code>, and <code>day</code> variables were removed to save space in the output.</p>
<pre><code>&gt; ruf &lt;- read.csv("RuffeSLRH.csv") %&gt;%
    filterD(month==7) %&gt;%
    mutate(fYear=factor(year),logW=log10(wt),logL=log10(tl)) %&gt;%
    select(-fishID,-month,-day)
&gt; headtail(ruf)

     year  tl   wt fYear      logW     logL
1    1988  78  6.0  1988 0.7781513 1.892095
2    1988  81  7.0  1988 0.8450980 1.908485
3    1988  82  7.0  1988 0.8450980 1.913814
1936 2004 137 28.0  2004 1.4471580 2.136721
1937 2004 143 31.4  2004 1.4969296 2.155336
1938 2004 174 82.4  2004 1.9159272 2.240549</code></pre>
<p>For the first example below, only fish from 1990, 1995, and 2000 were examined. In the second example below, fish from 1992 to 1995 were examined.</p>
<pre><code>&gt; ruf1 &lt;- filterD(ruf,year %in% c(1990,1995,2000))
&gt; ruf2 &lt;- filterD(ruf,year %in% 1992:1995)</code></pre>
</section>
<section id="full-model" class="level2" data-number="D.3">
<h2 data-number="D.3" class="anchored" data-anchor-id="full-model"><span class="header-section-number">D.3</span> Full Model</h2>
<p>The number of dummy variables required to represent kk groups is k−1k−1. Thus, in Chapter 7 of <strong>IFAR</strong>, only one dummy variable was required to represent the two groups. In this example, three groups (the years) are being examined and, thus, two dummy variables are needed. For example, <code>lm()</code> will ultimately treat the “1990” group as the reference group and create two dummy variables as follows</p>
<p>fYear1995={1, if captured in 19950, if NOT captured in 1995fYear1995={1, if captured in 19950, if NOT captured in 1995</p>
<p>fYear2000={1, if captured in 20000, if NOT captured in 2000fYear2000={1, if captured in 20000, if NOT captured in 2000</p>
<p>These dummy variables are each combined with the log10(L)log10(L) covariate to construct the following ultimate full model</p>
<p>log10(Wi)=log10(α)+βlog10(Li)+δ1fYear1995+δ2fYear2000+γ1fYear1995∗log10(Li)+γ2fYear2000∗log10(Li)+ϵi(1)log10(Wi)=log10(α)+βlog10(Li)+δ1fYear1995+δ2fYear2000+γ1fYear1995∗log10(Li)+γ2fYear2000∗log10(Li)+ϵi(1)</p>
<p>Substitution of appropriate values for the dummy variables into Equation 1 shows how Equation 1 simultaneously represents the weight-length relationship regressions for all three years (Table 1). From these submodels, it is apparent that αα is the y-intercept for the reference (e.g., 1990) group, ββ is the slope for the reference group, δiδi is the difference in y-intercepts between the iith and reference groups, and γiγi is the difference in slopes between the iith and reference groups. By extension, the interaction variables measure differences in slopes and the dummy variables measure differences in y-intercepts.</p>
<p>Table 1: The submodels by capture year represented by the full model.</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Year</strong></th>
<th style="text-align: left;"><strong>fYear1995</strong></th>
<th style="text-align: left;"><strong>fYear2000</strong></th>
<th style="text-align: left;"><strong>Submodel (</strong>log10(Wi)=log10(Wi)=)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1990</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">log10(α)+βlog10(Li)log10(α)+βlog10(Li)</td>
</tr>
<tr class="even">
<td style="text-align: left;">1995</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">(log10(α)+δ1)+(β+γ1)∗log10(Li)(log10(α)+δ1)+(β+γ1)∗log10(Li)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2000</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">(log10(α)+δ2)+(β+γ2)∗log10(Li)(log10(α)+δ2)+(β+γ2)∗log10(Li)</td>
</tr>
</tbody>
</table>
<p>The model in Equation 1 is fit with <code>lm()</code> using a formula of the form <code>y~x*factor</code> exactly as described in Chapter 7 of <strong>IFAR</strong> (again noting that <code>lm()</code> will create the appropriate dummy and interaction variables).</p>
<pre><code>&gt; fit1 &lt;- lm(logW~logL*fYear,data=ruf1)</code></pre>
<p>The linearity and homoscedasticity assumptions (Figure 1-Left) and normality assumption (Figure 1-Right) are largely met with this model.</p>
<pre><code>&gt; residPlot(fit1,legend=FALSE)</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/weightlength/index_files/figure-html/FullResidPlot-1.png" class="img-fluid" alt=""></p>
<p>Figure 1: Modified residual plot (Left) and histogram of residuals (Right) from fitting a dummy variable regression to the log-transformed weights and lengths of Ruffe captured in 1990, 1995, and 2000.</p>
<p>An ANOVA table is constructed (using <code>Anova()</code> from <code>car</code>) and interpreted (sequentially starting at the bottom of the table) as described in Chapter 7 of <strong>IFAR</strong>.</p>
<pre><code>&gt; Anova(fit1)

Anova Table (Type II tests)

Response: logW
           Sum Sq  Df   F value    Pr(&gt;F)
logL       43.529   1 22278.435 &lt; 2.2e-16
fYear       0.451   2   115.429 &lt; 2.2e-16
logL:fYear  0.052   2    13.395 2.159e-06
Residuals   0.971 497                    </code></pre>
<p>From these results it is apparent that the interaction term is a significant predictor in the model. In relation to Equation 1 this suggests that at least one of γ1γ1 or γ2γ2 is significantly different than zero, which implies that the slope of the relationship for fish captured in 1995, 2000, or both differs significantly from the slope for fish captured in 1990. Additionally, it is possible that the slopes for fish captured in 1995 and 2000 also differ, but this cannot be assessed with this model.</p>
<p>The ANOVA table for the fit of the full model is useful for determining if there is some difference in the regression model parameters among groups, but it cannot specifically identify where those differences occur. Specific differences are identified in the next section.</p>
</section>
<section id="pinpointing-specific-differences-among-slopes" class="level2" data-number="D.4">
<h2 data-number="D.4" class="anchored" data-anchor-id="pinpointing-specific-differences-among-slopes"><span class="header-section-number">D.4</span> <strong>Pinpointing Specific Differences Among Slopes</strong></h2>
<p>No simple method exists (such as Tukey’s Honestly Significant Difference (HSD) method) for comparing slopes among all pairs of groups while controlling for an increase in experimentwise error due to multiple comparisons. One strategy to perform these tests, though, is to fit the DVR as in the previous section and extract all of the p-values for comparisons of slopes to the reference level. Another model is then fit where the reference level has been changed and all p-values for comparisons of slopes to this level are extracted. This process is repeated until p-values for all pairwise comparisons have been extracted. The set of p-values from these comparisons is then submitted to procedures, such as one of the sequential Bonferroni or false discovery rate procedures, that are designed to adjust a set of p-values for multiple comparisons.</p>
<p>Controlling the experimentwise error rate for multiple comparisons is easily accomplished in R with <code>p.adjust()</code>. However, the sequential resetting of the reference level, fitting a new model, and extracting the p-values from all slope comparisons is tedious, especially for many groups. Fortunately, <code>compSlopes()</code> from <code>FSA</code> automates the tedious computation of the set of p-values and use of <code>p.adjust()</code> to control the experimentwise error rate.</p>
<p>The <code>compSlopes()</code> function requires a DVR model fit from <code>lm()</code> as its first argument. The method to control for multiple comparisons is set with <code>method=</code> and may be any of the methods returned by <code>p.adjust.methods()</code> (see <code>?p.adjust</code>).</p>
<pre><code>&gt; compSlopes(fit1)

Multiple Slope Comparisons (using the 'holm' adjustment)

  comparison     diff  95% LCI  95% UCI p.unadj   p.adj
1  1995-1990 -0.17186 -0.27049 -0.07324 0.00067 0.00134
2  2000-1990 -0.22852 -0.31738 -0.13965 0.00000 0.00000
3  2000-1995 -0.05665 -0.15236  0.03905 0.24538 0.24538


Slope Information (using the 'holm' adjustment)

  level  slopes 95% LCI 95% UCI p.unadj p.adj
3  2000 2.79665 2.73611 2.85719       0     0
2  1995 2.85330 2.77918 2.92743       0     0
1  1990 3.02516 2.96011 3.09022       0     0</code></pre>
<p>Two sets of results are returned by <code>compSlopes()</code>. The top set of results shows the difference in slopes (<code>diff</code>), unadjusted confidence interval for the difference in slopes (<code>95% LCI</code> and <code>95% UCI</code>), and unadjusted (<code>p.unadj</code>) and adjusted (<code>p.adj</code>) p-values for testing that the difference in slopes is not zero. These results show that the slope for 1990 is significantly greater than the slopes for 1995 and 2000, and that the slopes for 1995 and 2000 do not differ significantly.</p>
<p>The bottom set of results shows the slope (<code>slope</code>), unadjusted confidence interval for the slope (<code>95% LCI</code> and <code>95% UCI</code>), and unadjusted (<code>p.unadj</code>) and adjusted (<code>p.adj</code>) p-values for testing that the slope is not equal to zero. In this case, this output is primarily for completeness, as these hypothesis are not generally of interest with weight-length relationship regressions.</p>
</section>
<section id="a-summary-plot" class="level2" data-number="D.5">
<h2 data-number="D.5" class="anchored" data-anchor-id="a-summary-plot"><span class="header-section-number">D.5</span> A Summary Plot</h2>
<p>A plot that shows the transformed weight-length data with best-fit lines for each year superimposed (Figure 2) is constructed with the code below. This code follows that found in the <strong>IFAR</strong> book with the exception that <code>col2rgbt()</code> from <code>FSA</code> is used to add transparency to each color in a vector of colors.</p>
<pre><code>&gt; ## Base plot
&gt; clrs1 &lt;- c("black","red","blue")
&gt; clrs2 &lt;- col2rgbt(clrs1,1/4)
&gt; plot(logW~logL,data=ruf1,pch=19,col=clrs2[fYear],
       xlab="log(Total Length)",ylab="log(Weight)")
&gt; ## Fitted lines
&gt; ( cfs &lt;- coef(fit1) )

   (Intercept)           logL      fYear1995      fYear2000 logL:fYear1995 
    -4.9144676      3.0251636      0.2817809      0.3942964     -0.1718633 
logL:fYear2000 
    -0.2285159 

&gt; minx &lt;- min(ruf1$logL)
&gt; maxx &lt;- max(ruf1$logL)
&gt; curve(cfs[1]+cfs[2]*x,from=minx,to=maxx,col=clrs1[1],lwd=2,add=TRUE)
&gt; curve((cfs[1]+cfs[3])+(cfs[2]+cfs[5])*x,from=minx,to=maxx,col=clrs1[2],lwd=2,add=TRUE)
&gt; curve((cfs[1]+cfs[4])+(cfs[2]+cfs[6])*x,from=minx,to=maxx,col=clrs1[3],lwd=2,add=TRUE)
&gt; ## Add legend
&gt; legend("topleft",levels(ruf1$fYear),pch=19,col=clrs1)</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/weightlength/index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" alt=""></p>
<p>Figure 2: Log-transformed weight versus log-transformed length of Ruffe separated by capture year.</p>
</section>
<section id="pinpointing-specific-differences-among-intercepts" class="level2" data-number="D.6">
<h2 data-number="D.6" class="anchored" data-anchor-id="pinpointing-specific-differences-among-intercepts"><span class="header-section-number">D.6</span> Pinpointing Specific Differences Among Intercepts</h2>
<p>When a difference in slopes exists, as in the previous example, it generally does not make sense to compare intercepts. However, if the slopes do not differ, then testing for differences in intercepts becomes important because, with parallel lines (i.e., same slopes), a difference in intercepts implies that the mean value of the response variable differs at <em>every</em> value of the explanatory variable.</p>
<p>The example below fits a DVR of the weight-length relationship regressions for the years from 1992 to 1995 (data.frame constructed <a href="http://derekogle.com/IFAR/supplements/weightlength/index.html#data=used-in-this-supplement">above</a>). In this example, the interaction term is not a significant predictor which indicates that none of the slopes differ. However, the term related to the factor variable is significant, which implies that at least one of the δiδi is different from zero. Thus, the y-intercept for at least of 1993, 1994, or 1995 differs from the y-intercept for 1992 (the reference level).</p>
<pre><code>&gt; fit2 &lt;- lm(logW~logL*fYear,data=ruf2)
&gt; Anova(fit2)

Anova Table (Type II tests)

Response: logW
           Sum Sq  Df    F value Pr(&gt;F)
logL       75.798   1 45594.0523 &lt;2e-16
fYear       0.326   3    65.4373 &lt;2e-16
logL:fYear  0.008   3     1.6373 0.1793
Residuals   1.235 743                  </code></pre>
<p>The same problem of incomplete comparisons and increasing experimentwise error occurs here with the y-intercepts as occurred with the slopes above. The solution, however, is different here because the y-intercept is a point estimate, whereas the slope estimates a rate of change. In this case, Tukey’s HSD method can be used to determine which pairs of y-intercepts differ. However, the observed values need to be adjusted to a single values of the covariate.</p>
<p>The adjusted value for an individual is computed by adding the individual’s residual from the full model to the predicted value of the response variable (from the full model gieven the individuals group) at a common covariate value. Visually, this adjustment may be thought of as sliding each point along the regression line (for the individual’s group) to a common value (for all groups) along the x-axis.</p>
<p>The <code>compIntercepts()</code> function from <code>FSA</code> performs these adjustments and applies Tukey’s HSD procedure to the adjusted values. The <code>compIntercepts()</code> function requires the fitted DVR as the first argument. By default, the response variables are are adjusted to the mean value of the covariate unless a value is given to <code>common.cov=</code>. For example, the actual y-intercepts will be used if <code>common.cov=0</code>. Also note that a warning is given if the DVR model contains an interaction term, though <code>compIntercepts()</code> will adjust for this by fitting a new model without the nonsignificant interaction term.</p>
<pre><code>&gt; compIntercepts(fit2)

Warning: Removed an interaction term from 'mdl' (i.e., assumed
 parallel lines) to test intercepts.

Tukey HSD on means adjusted assuming parallel lines

  comparison          diff     95% LCI      95% UCI     p.adj
1  1993-1992 -0.0560847608 -0.06723042 -0.044939103 0.0000000
2  1994-1992 -0.0609843518 -0.07392816 -0.048040541 0.0000000
3  1995-1992 -0.0616068456 -0.07461176 -0.048601927 0.0000000
4  1994-1993 -0.0048995910 -0.01528465  0.005485465 0.6176269
5  1995-1993 -0.0055220848 -0.01598321  0.004939036 0.5254957
6  1995-1994 -0.0006224938 -0.01298177  0.011736778 0.9992208


Mean logW when logL=2.012621

    1992     1993     1994     1995 
1.171924 1.115839 1.110939 1.110317 </code></pre>
<p>Two sets of results are returned by <code>compIntercepts()</code>. The top set of results shows the difference in y-intercepts (<code>diff</code>), unadjusted confidence interval for the difference in y-intercepts (<code>95% LCI</code> and <code>95% UCI</code>), and adjusted (<code>p.adj</code>) p-values for testing that the difference in y-intercepts is not zero. These results show that the y-intercept for 1992 is significantly greater than the y-intercepts for all other years, which did not differ significantly.</p>
<p>The bottom set of results shows the mean value of the response variable at a common value of the covariate for each group. For example, the mean log10(W)log10(W) for when log10(L)log10(L)=2.012621 for fish captured in 1992 is 1.171924.</p>
<pre><code>&gt; ## Base plot
&gt; clrs1 &lt;- c("black","red","blue","green")
&gt; clrs2 &lt;- col2rgbt(clrs1,1/4)
&gt; plot(logW~logL,data=ruf2,pch=19,col=clrs2[fYear],
       xlab="log(Total Length)",ylab="log(Weight)")
&gt; ## Fitted lines
&gt; ( cfs &lt;- coef(fit2) )

   (Intercept)           logL      fYear1993      fYear1994      fYear1995 
  -4.553035394    2.846025564   -0.197272960   -0.189460113   -0.079651305 
logL:fYear1993 logL:fYear1994 logL:fYear1995 
   0.068720265    0.062584797    0.007274738 

&gt; minx &lt;- min(ruf2$logL)
&gt; maxx &lt;- max(ruf2$logL)
&gt; curve(cfs[1]+cfs[2]*x,from=minx,to=maxx,col=clrs1[1],lwd=2,add=TRUE)
&gt; curve((cfs[1]+cfs[3])+(cfs[2]+cfs[6])*x,from=minx,to=maxx,col=clrs1[2],lwd=2,add=TRUE)
&gt; curve((cfs[1]+cfs[4])+(cfs[2]+cfs[7])*x,from=minx,to=maxx,col=clrs1[3],lwd=2,add=TRUE)
&gt; curve((cfs[1]+cfs[5])+(cfs[2]+cfs[8])*x,from=minx,to=maxx,col=clrs1[4],lwd=2,add=TRUE)
&gt; ## Add legend
&gt; legend("topleft",levels(ruf2$fYear),pch=19,col=clrs1)</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/weightlength/index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" alt=""></p>
<p>Figure 3: Log-transformed weight versus log-transformed length of Ruffe separated by capture year.</p>
<hr>
</section>
<section id="reproducibility-information" class="level2" data-number="D.7">
<h2 data-number="D.7" class="anchored" data-anchor-id="reproducibility-information"><span class="header-section-number">D.7</span> Reproducibility Information</h2>
<ul>
<li><p><strong>Compiled Date:</strong> Thu Nov 05 2015</p></li>
<li><p><strong>Compiled Time:</strong> 8:54:13 PM</p></li>
<li><p><strong>R Version:</strong> R version 3.2.2 (2015-08-14)</p></li>
<li><p><strong>System:</strong> Windows, i386-w64-mingw32/i386 (32-bit)</p></li>
<li><p><strong>Base Packages:</strong> base, datasets, graphics, grDevices, methods, stats, utils</p></li>
<li><p><strong>Required Packages:</strong> FSA, dplyr, car, captioner, knitr and their dependencies (assertthat, DBI, digest, evaluate, formatR, gdata, gplots, graphics, grDevices, highr, Hmisc, lazyeval, magrittr, markdown, MASS, methods, mgcv, nnet, pbkrtest, plotrix, plyr, quantreg, R6, Rcpp, sciplot, stats, stringr, tools, utils, yaml)</p></li>
<li><p><strong>Other Packages:</strong> captioner_2.2.3, car_2.1-0, dplyr_0.4.3, extrafont_0.17, FSA_0.8.4, knitr_1.11, rmarkdown_0.8.1</p></li>
<li><p><strong>Loaded-Only Packages:</strong> assertthat_0.1, DBI_0.3.1, digest_0.6.8, evaluate_0.8, extrafontdb_1.0, formatR_1.2.1, gdata_2.17.0, grid_3.2.2, gtools_3.5.0, htmltools_0.2.6, lattice_0.20-33, lazyeval_0.1.10, lme4_1.1-10, magrittr_1.5, MASS_7.3-44, Matrix_1.2-2, MatrixModels_0.4-1, mgcv_1.8-8, minqa_1.2.4, nlme_3.1-122, nloptr_1.0.4, nnet_7.3-11, parallel_3.2.2, pbkrtest_0.4-2, plyr_1.8.3, quantreg_5.19, R6_2.1.1, Rcpp_0.12.1, Rttf2pt1_1.3.3, SparseM_1.7, splines_3.2.2, stringi_1.0-1, stringr_1.0.0, tools_3.2.2, yaml_2.1.13</p></li>
<li><p><strong>Links:</strong> <a href="http://derekogle.com/IFAR/supplements/weightlength/weightlengthDVR.R">Script</a> / <a href="http://derekogle.com/IFAR/supplements/weightlength/index.Rmd">RMarkdown</a></p></li>
</ul>
<hr>
</section>
<section id="references" class="level2" data-number="D.8">
<h2 data-number="D.8" class="anchored" data-anchor-id="references"><span class="header-section-number">D.8</span> References</h2>
<p>Ogle, D. H., and I. J. Winfield. 2009. Ruffe length-weight relationships with a proposed standard weight equation. North American Journal of Fisheries Management 29:850–858.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./installPackages.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Install packages in R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./basicstats.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title"><strong>Basic Data Manipulations</strong></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>