<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>fishStats - Appendix F — Recruitment and logistic model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./basicstats.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Appendix F — Recruitment and logistic model</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./" class="sidebar-logo-link">
      <img src="./FAO_logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">fishStats</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/lugoga/ecasData" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><strong>Installation</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Rlanguage.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title"><strong>R as a Programming Language</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rstudio.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title"><strong>Getting Started with RStudio</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title"><strong>Packages</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title"><strong>Data Entry and Management</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./loadingData.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title"><strong>Loading Data and Data Cleaning</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sample.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sample Data in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicFishStats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title"><strong>Basic Fisheries Statistics</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicFishPlotting.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title"><strong>Plotting Fisheries Data</strong></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulate.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulate Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installR.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">R language installation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installRstudio.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title"><strong>What is RStudio?</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installPackages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Install packages in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lw.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title"><strong>Weight-Length Relationships</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basicstats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title"><strong>Basic Data Manipulations</strong></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./recruitment.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Recruitment and logistic model</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#required-packages-for-this-supplement" id="toc-required-packages-for-this-supplement" class="nav-link active" data-scroll-target="#required-packages-for-this-supplement"> <span class="header-section-number">F.0.1</span> <strong>Required Packages for this Supplement</strong></a></li>
  <li><a href="#data-used-in-this-supplement" id="toc-data-used-in-this-supplement" class="nav-link" data-scroll-target="#data-used-in-this-supplement"> <span class="header-section-number">F.0.2</span> <strong>Data Used in this Supplement</strong></a></li>
  <li><a href="#maturity-data" id="toc-maturity-data" class="nav-link" data-scroll-target="#maturity-data"> <span class="header-section-number">F.1</span> <strong>Maturity Data</strong></a></li>
  <li><a href="#modeling-with-raw-data" id="toc-modeling-with-raw-data" class="nav-link" data-scroll-target="#modeling-with-raw-data"> <span class="header-section-number">F.2</span> <strong>Modeling with Raw Data</strong></a>
  <ul class="collapse">
  <li><a href="#fitting-the-logistic-regression-model" id="toc-fitting-the-logistic-regression-model" class="nav-link" data-scroll-target="#fitting-the-logistic-regression-model"> <span class="header-section-number">F.2.1</span> <strong>Fitting the Logistic Regression Model</strong></a></li>
  <li><a href="#predicted-probability-of-being-mature" id="toc-predicted-probability-of-being-mature" class="nav-link" data-scroll-target="#predicted-probability-of-being-mature"> <span class="header-section-number">F.2.2</span> <strong>Predicted Probability of Being Mature</strong></a></li>
  <li><a href="#a-summary-plot" id="toc-a-summary-plot" class="nav-link" data-scroll-target="#a-summary-plot"> <span class="header-section-number">F.2.3</span> <strong>A Summary Plot</strong></a></li>
  <li><a href="#length--or-age-at-maturity" id="toc-length--or-age-at-maturity" class="nav-link" data-scroll-target="#length--or-age-at-maturity"> <span class="header-section-number">F.2.4</span> <strong>Length- or Age-at-Maturity</strong></a></li>
  </ul></li>
  <li><a href="#modeling-with-summarized-data" id="toc-modeling-with-summarized-data" class="nav-link" data-scroll-target="#modeling-with-summarized-data"> <span class="header-section-number">F.3</span> <strong>Modeling with Summarized Data</strong></a></li>
  <li><a href="#comparing-logistic-regressions-between-groups" id="toc-comparing-logistic-regressions-between-groups" class="nav-link" data-scroll-target="#comparing-logistic-regressions-between-groups"> <span class="header-section-number">F.4</span> <strong>Comparing Logistic Regressions Between Groups</strong></a>
  <ul class="collapse">
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting"> <span class="header-section-number">F.4.1</span> <strong>Model Fitting</strong></a></li>
  <li><a href="#comparing-lengths--or-ages-at-maturity" id="toc-comparing-lengths--or-ages-at-maturity" class="nav-link" data-scroll-target="#comparing-lengths--or-ages-at-maturity"> <span class="header-section-number">F.4.2</span> <strong>Comparing Lengths- or Ages-at-Maturity</strong></a></li>
  <li><a href="#a-summary-plot-1" id="toc-a-summary-plot-1" class="nav-link" data-scroll-target="#a-summary-plot-1"> <span class="header-section-number">F.4.3</span> <strong>A Summary Plot</strong></a></li>
  </ul></li>
  <li><a href="#reproducibility-information" id="toc-reproducibility-information" class="nav-link" data-scroll-target="#reproducibility-information"> <span class="header-section-number">F.5</span> <strong>Reproducibility Information</strong></a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"> <span class="header-section-number">F.6</span> <strong>References</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Appendix F — Recruitment and logistic model</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>The length-, weight-, or age-at-maturity is important to monitor for fish populations because these metrics are closely tied to reproductive potential and respond to changes in inter- and intra-specific densities and resource availability (Pope et al.&nbsp;2010). Methods for modeling the relationship between maturity stage and length is demonstrated in this supplement. Results from these modeled relationships are then used to calculate metrics such as length at 50% maturity. These methods extend directly to use with age or weight data.</p>
<p>&nbsp;</p>
<section id="required-packages-for-this-supplement" class="level3" data-number="F.0.1">
<h3 data-number="F.0.1" class="anchored" data-anchor-id="required-packages-for-this-supplement"><span class="header-section-number">F.0.1</span> <strong>Required Packages for this Supplement</strong></h3>
<p>Functions used in this supplement require the packages shown below.</p>
<pre><code>&gt; library(FSA)
&gt; library(magrittr)
&gt; library(dplyr)
&gt; library(lubridate)
&gt; library(car)</code></pre>
</section>
<section id="data-used-in-this-supplement" class="level3" data-number="F.0.2">
<h3 data-number="F.0.2" class="anchored" data-anchor-id="data-used-in-this-supplement"><span class="header-section-number">F.0.2</span> <strong>Data Used in this Supplement</strong></h3>
<p>The total length (<code>length</code>; to the nearest cm), <code>age</code> (years), and <code>maturity</code> (<code>Immature</code> and <code>Mature</code>) state of female Yelloweye Rockfish (<em>Sebastes rubberimus</em>) collected from along the Oregon coast are recorded in <code>YERockFish.csv</code> (<a href="https://github.com/droglenc/FSAdata/blob/master/data-raw/YERockfish.csv">view</a>, <a href="https://raw.githubusercontent.com/droglenc/FSAdata/master/data-raw/YERockfish.csv">download</a>, <a href="http://derekogle.com/fishR/data/data-html/YERockfish.html">meta-data</a>).</p>
<pre><code>&gt; df &lt;- read.csv("YERockfish.csv")

&gt; str(df)

'data.frame':   158 obs. of  5 variables:
 $ date    : Factor w/ 71 levels "10/1/2003","10/2/2003",..: 66 9 38 25 60 6 3..
 $ length  : int  31 32 32 32 32 33 33 34 34 34 ...
 $ age     : int  10 6 11 11 13 9 10 8 10 11 ...
 $ maturity: Factor w/ 2 levels "Immature","Mature": 1 1 1 1 1 1 1 1 1 1 ...
 $ stage   : Factor w/ 9 levels "1","2","3","4",..: 1 1 1 2 2 1 1 1 1 1 ...</code></pre>
<p>The date of capture was also recorded. A new variable that indicates whether the fish was captured before 2002 or in 2002 and after is needed for use in a later example that compares the relationship between maturity and length between two groups. This conversion requires that <code>date</code> be converted to a format that R will recognize as a date. The <code>as.POSIXct()</code> function does this conversion, taking the original dates as its first argument. Additionally, a string is given to <code>format=</code> that describes the format of the dates in the original variable. The codes that may be used in this string are described in <code>?strptime</code>. Common codes used with fisheries data are</p>
<ul>
<li><p><code>%m</code>: month as a number,</p></li>
<li><p><code>%b</code>: month as an abbreviated name (e.g., <code>Jan</code>, <code>Feb</code>),</p></li>
<li><p><code>%d</code>: day of the month,</p></li>
<li><p><code>%Y</code>: four-digit year (e.g., <code>2015</code>), and</p></li>
<li><p><code>%y</code>: two-digit (i.e., without the century) year (e.g., <code>15</code>).</p></li>
</ul>
<p>These format codes are separated by the characters that separate the fields in the original date variable (e.g., <code>/</code>, <code>-</code>).</p>
<p>An examination of <code>date</code> shows that the dates are in month as a number, day of the month, and four digit year format separated by “forward slashes.”</p>
<pre><code>&gt; headtail(df)

         date length age maturity stage
1    9/2/2003     31  10 Immature     1
2   10/7/2002     32   6 Immature     1
3   7/18/2000     32  11 Immature     1
156 8/18/2002     67  50   Mature     6
157 10/7/2002     68  88   Mature     6
158 4/23/2001     70  66   Mature     4</code></pre>
<p>Thus, <code>date</code> is converted below to a date format that R will recognize.</p>
<pre><code>&gt; df %&lt;&gt;% mutate(date=as.POSIXct(date,format="%m/%d/%Y"))
&gt; str(df)

'data.frame':   158 obs. of  5 variables:
 $ date    : POSIXct, format: "2003-09-02" "2002-10-07" ...
 $ length  : int  31 32 32 32 32 33 33 34 34 34 ...
 $ age     : int  10 6 11 11 13 9 10 8 10 11 ...
 $ maturity: Factor w/ 2 levels "Immature","Mature": 1 1 1 1 1 1 1 1 1 1 ...
 $ stage   : Factor w/ 9 levels "1","2","3","4",..: 1 1 1 2 2 1 1 1 1 1 ...</code></pre>
<p>The year of capture may then be extracted from <code>date</code> with <code>year()</code> from <code>lubridate</code> (Grolemund and Wickham 2011). Note that the month could be extracted with <code>month()</code>, day of the month with <code>mday()</code>, and day of the year (1-366) with <code>yday()</code>. A variable (<code>era</code>) that indicates the era (<code>pre-2002</code> or <code>2002 and after</code>) is then added to the data.frame as a factor.</p>
<pre><code>&gt; df %&lt;&gt;% mutate(year=year(date),
                 era=ifelse(year&lt;2002,"pre-2002","2002 and after"),
                 era=factor(era,levels=c("pre-2002","2002 and after")))
&gt; headtail(df)

          date length age maturity stage year            era
1   2003-09-02     31  10 Immature     1 2003 2002 and after
2   2002-10-07     32   6 Immature     1 2002 2002 and after
3   2000-07-18     32  11 Immature     1 2000       pre-2002
156 2002-08-18     67  50   Mature     6 2002 2002 and after
157 2002-10-07     68  88   Mature     6 2002 2002 and after
158 2001-04-23     70  66   Mature     4 2001       pre-2002</code></pre>
<p>Finally, <code>maturity</code> was not recorded for several individuals, which were removed from further analysis.</p>
<pre><code>&gt; df %&lt;&gt;% filterD(!is.na(maturity))</code></pre>
<p>&nbsp;</p>
</section>
<section id="maturity-data" class="level2" data-number="F.1">
<h2 data-number="F.1" class="anchored" data-anchor-id="maturity-data"><span class="header-section-number">F.1</span> <strong>Maturity Data</strong></h2>
<p>Raw maturity data generally consists of a maturity statement (either “mature” or “immature”), size (length or weight), age, sex, and other variables as needed (e.g., capture date, capture location) recorded for individual fish. The maturity variable may need to be derived from more specific data about the “stage of maturation” recorded for each fish. Often, maturity will be recorded as a dummy or indicator variable – “0” for immature and “1” for mature – but this is not required for most modern software. Sex is an important variable to record as maturity should be analyzed separately for each sex (Pope et al.&nbsp;2010).</p>
<p>Summarized maturity data consists of the proportion of individuals that are mature within each age or length category. Age categories are generally the recorded ages, whereas recorded lengths are often categorized into bins. Age or length categories should be as narrow as possible but include enough individuals such that the proportion mature in each bin is reliably estimated.</p>
<p>In this supplement, the total length of the Rockfish was measured to the nearest cm. Length categories that were 2 cm were chosen to summarize the data to provide reasonable sample sizes (&gt;10&gt;10 fish) in the length ranges where the proportion of mature fish is most rapidly changing. These length categories are added to the data.frame with <code>lencat()</code> below (as described in Chapter 2 of the <strong>IFAR</strong> book).</p>
<pre><code>&gt; df %&lt;&gt;% mutate(lcat2=lencat(length,w=2))
&gt; headtail(df)

          date length age maturity stage year            era lcat2
1   2003-09-02     31  10 Immature     1 2003 2002 and after    30
2   2002-10-07     32   6 Immature     1 2002 2002 and after    32
3   2000-07-18     32  11 Immature     1 2000       pre-2002    32
146 2002-08-18     67  50   Mature     6 2002 2002 and after    66
147 2002-10-07     68  88   Mature     6 2002 2002 and after    68
148 2001-04-23     70  66   Mature     4 2001       pre-2002    70</code></pre>
<p>The frequency of mature and immature fish in each length category is computed with <code>xtabs()</code> below. The raw frequencies are converted to “row proportions” with <code>prop.table()</code> to see the proportion of fish within each length category that are mature. Finally, a plot of the proportion of mature fish is constructed (Figure 1).</p>
<pre><code>&gt; freq &lt;- xtabs(~lcat2+maturity,data=df)
&gt; props &lt;- prop.table(freq,margin=1)
&gt; round(props,3)   # for display only

     maturity
lcat2 Immature Mature
   30    1.000  0.000
   32    1.000  0.000
   34    1.000  0.000
   36    0.556  0.444
   38    0.625  0.375
   40    0.333  0.667
   42    0.077  0.923
   44    0.077  0.923
   46    0.036  0.964
   48    0.062  0.938
   50    0.000  1.000
   52    0.000  1.000
   54    0.000  1.000
   56    0.000  1.000
   58    0.000  1.000
   60    0.000  1.000
   62    0.000  1.000
   64    0.000  1.000
   66    0.000  1.000
   68    0.000  1.000
   70    0.000  1.000

&gt; plot(props[,"Mature"]~as.numeric(rownames(props)),pch=19,
       xlab="Total Length (cm)",ylab="Proportion Mature")</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/maturity/index_files/figure-html/sumLength-1.png" class="img-fluid" alt=""></p>
<p>Figure 1: Proportion of female Yelloweye Rockfish that were mature in each 2-cm length category.</p>
<p>These results show that the percentage of mature female Yellow Rockfish increases quickly between 34 and 42 cm.</p>
<p>&nbsp;</p>
</section>
<section id="modeling-with-raw-data" class="level2" data-number="F.2">
<h2 data-number="F.2" class="anchored" data-anchor-id="modeling-with-raw-data"><span class="header-section-number">F.2</span> <strong>Modeling with Raw Data</strong></h2>
<section id="fitting-the-logistic-regression-model" class="level3" data-number="F.2.1">
<h3 data-number="F.2.1" class="anchored" data-anchor-id="fitting-the-logistic-regression-model"><span class="header-section-number">F.2.1</span> <strong>Fitting the Logistic Regression Model</strong></h3>
<p>Raw maturity data is generally summarized with a logistic regression. A logistic regression is conducted with a binomial response variable and, generally, a quantitative explanatory variable. The relationship between the probability of “success” (pp) and the explanatory variable (length or age) is generally not linear (primarily due to the constraint that the probability is between 0 and 1). This relationship can be linearized by first transforming pp to the odds (i.e., p1−pp1−p). The odds related the probability of “successes” to “failures.” For example, an odds of 1 indicates that there is an equal probability of success and failure, whereas an odds of 3 indicates that the probability of success is three times the probability of failure.</p>
<p>The transformation to a linear relationship is completed by computing the logarithm of the odds (i.e., log(p1−p)log(p1−p)). The complete transformation from pp to log(p1−p)log(p1−p) is called the <em>logit</em> transformation.</p>
<p>Thus, the linear model in a logistic regression models the log odds as a function of an explanatory variable, XX, with</p>
<p>log(p1−p)=α+β1X(1)log(p1−p)=α+β1X(1)</p>
<p>In maturity analyses, the logistic regression is used to model the log odds of being mature as a function of either length or age. It will be shown later in this supplement how the log odds of being mature are back-transformed to the probability of being mature.</p>
<p>Logistic regressions are fit with <code>glm()</code>, rather than the <code>lm()</code> used in the <strong>IFAR</strong> book. For a logistic regression the first argument to <code>glm()</code> is a formula of the form <code>factor~quant</code> where <code>factor</code> and <code>quant</code> generically represent factor and quantitative variables, respectively. The data.frame that contains <code>factor</code> and <code>quant</code> is given to <code>data=</code>. Finally, <code>glm()</code> is forced to use the logit transformation and fit a logistic regression by including <code>family=binomial</code>. For example, the <code>glm()</code> code below will model the log odds of being mature as a function of the length of the Rockfish.</p>
<pre><code>&gt; glm1 &lt;- glm(maturity~length,data=df,family=binomial)</code></pre>
<p>Parameter estimates are extracted from the <code>glm()</code> object with <code>coef()</code>. Confidence intervals for the parameters of a logistic regression are best estiamted with bootstrapping (rather than normal theory). Bootstrapping is performed with <code>bootCase()</code> from <code>car</code> as described in Chapter 12 of the <strong>IFAR</strong> book.</p>
<pre><code>&gt; bcL &lt;- bootCase(glm1,B=1000)
&gt; cbind(Ests=coef(glm1),confint(bcL))

                   Ests     95% LCI     95% UCI
(Intercept) -16.9482593 -29.0623105 -11.8152911
length        0.4371786   0.3108028   0.7400613</code></pre>
<p>The estimated slope indicates that a 1 cm increase in the length of the Yelloweye Rockfish will result in a 0.437 increase in the log odds that the Rockfish is mature. Changes in log odds are difficult to interpret. However, the back-transformed slope is interpreted as a multiplicative change in the odds of being mature. For example, a 1 cm increase in the length of the Yelloweye Rockfish will result in a 1.548 (i.e., e0.437e0.437) times increase in the odds that the Rockfish is mature.</p>
<p>&nbsp;</p>
</section>
<section id="predicted-probability-of-being-mature" class="level3" data-number="F.2.2">
<h3 data-number="F.2.2" class="anchored" data-anchor-id="predicted-probability-of-being-mature"><span class="header-section-number">F.2.2</span> <strong>Predicted Probability of Being Mature</strong></h3>
<p>The probability of a fish being mature given the observed value of the explanatory variable (xx) can be computed by solving Equation 1 for pp,</p>
<p>p=eα+β1x1+eα+β1(2)p=eα+β1x1+eα+β1(2)</p>
<p>This prediction is computed with <code>predict()</code>, which requires the <code>glm()</code> object as the first argument, a data.frame with the values of the explanatory variable for which to make the prediction as the second argument, and <code>type="response"</code> (which forces the prediction of the probability, rather than the log odds, of being mature). For example, the predicted probabilities of being mature for female Yelloweye Rockfish that are 32- and 42-cm total length are computed below.</p>
<pre><code>&gt; predict(glm1,data.frame(length=c(32,42)),type="response")

        1         2 
0.0493342 0.8042766 </code></pre>
<p>Confidence intervals for the predicted probability are formed by computing the prediction for each bootstrap sample and then extracting the values for the upper and lower 2.5% of these predictions. This process is most easily accomplished by forming a function that represents Equation 2 and then using <code>apply()</code> to apply that function to each row of the matrix containing the bootstrap samples. This is the same process as described in Chapter 12 of the <strong>IFAR</strong> book. The code below computes the 95% confidence intervals for the predicted probability of being mature for 32 cm long Yelloweye Rockfish.</p>
<pre><code>&gt; predP &lt;- function(cf,x) exp(cf[1]+cf[2]*x)/(1+exp(cf[1]+cf[2]*x))
&gt; p32 &lt;- apply(bcL,1,predP,x=32)
&gt; quantile(p32,c(0.025,0.975))

      2.5%      97.5% 
0.00313281 0.14033465 </code></pre>
<p>Thus, the probability that a 32 cm Yelloweye Rockfish is mature is between 0.003 and 0.140.</p>
<p>&nbsp;</p>
</section>
<section id="a-summary-plot" class="level3" data-number="F.2.3">
<h3 data-number="F.2.3" class="anchored" data-anchor-id="a-summary-plot"><span class="header-section-number">F.2.3</span> <strong>A Summary Plot</strong></h3>
<p>A plot that illustrates the fit of the logistic regression (Figure 2) is constructed in several steps. First, a base plot that depicts the raw data is constructed. Take special note here that <code>maturity</code> is forced to be numeric between 0 and 1 for the plot and transparent points (as described in Chapter 3 of the <strong>IFAR</strong> book) are used because there is considerable overplotting with the “discrete” maturity and length data.</p>
<pre><code>&gt; plot((as.numeric(maturity)-1)~length,data=df,
       pch=19,col=rgb(0,0,0,1/8),
       xlab="Total Length (cm)",ylab="Proportion Mature")</code></pre>
<p>Second, points that represent the proportion mature for each 2-cm length bin are added to the plot with <code>points()</code> (recall that the summaries in <code>props</code> were constructed above). Note that <code>pch=3</code> plots the points as “plus signs.”</p>
<pre><code>&gt; points(props[,"Mature"]~as.numeric(rownames(props)),pch=3)</code></pre>
<p>Finally, the fitted line from the logistic regression is added by first using the <code>glm()</code> object to predict the probability of being mature for lengths that span the range of observed lengths and then plotting these values as a line with <code>lines()</code>.</p>
<pre><code>&gt; lens &lt;- seq(30,70,length.out=99)
&gt; preds &lt;- predict(glm1,data.frame(length=lens),type="response")
&gt; lines(preds~lens,lwd=2)</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/maturity/index_files/figure-html/LogisticFit1-1.png" class="img-fluid" alt=""></p>
<p>Figure 2: Fitted logistic regression for the proportion of female Yelloweye Rockfish that are mature by total length.</p>
<p>&nbsp; &nbsp;</p>
</section>
<section id="length--or-age-at-maturity" class="level3" data-number="F.2.4">
<h3 data-number="F.2.4" class="anchored" data-anchor-id="length--or-age-at-maturity"><span class="header-section-number">F.2.4</span> <strong>Length- or Age-at-Maturity</strong></h3>
<p>A common metric in fisheries science is to find the length or age at which a certain percentage of fish are mature. For example, it is common to ask “what is the length or age at which 50% of the fish have reached maturity?” A general formula for computing this metric is found by solving Equation 1 for XX,</p>
<p>x=log(p1−p)−αβ1(3)x=log(p1−p)−αβ1(3)</p>
<p>In the common case of finding XX for 50% maturity (i.e., p=0.5p=0.5), Equation 3 reduces to</p>
<p>x=−αβ1(4)x=−αβ1(4)</p>
<p>The age at which 50% of the fish are mature is commonly symbolized as A50A50. Similarly, the length at which 90% of the fish are mature would be L90L90.</p>
<p>These calculations are simplified by creating a function to perform Equation 3.</p>
<pre><code>&gt; lrPerc &lt;- function(cf,p) (log(p/(1-p))-cf[[1]])/cf[[2]]</code></pre>
<p>This functions takes the coefficents from the <code>glm()</code> object as the first argument and the probability of interest (pp) as the second argument. As examples, the lengths at which 50% and 90% of the female Yelloweye Rockfish are mature are computed below.</p>
<pre><code>&gt; ( L50 &lt;- lrPerc(coef(glm1),0.5) )

[1] 38.76736

&gt; ( L90 &lt;- lrPerc(coef(glm1),0.9) )

[1] 43.79328</code></pre>
<p>Confidence intervals for these values are constructed from the bootstrap samples, similar to what was illustrated above for predicted values.</p>
<pre><code>&gt; bL50 &lt;- apply(bcL,1,lrPerc,p=0.5)
&gt; ( L50ci &lt;- quantile(bL50,c(0.025,0.975)) )

    2.5%    97.5% 
37.28749 40.10023 

&gt; bL90 &lt;- apply(bcL,1,lrPerc,p=0.9)
&gt; ( L90ci &lt;- quantile(bL90,c(0.025,0.975)) )

    2.5%    97.5% 
41.68692 45.92492 </code></pre>
<p>Thus, for example, the predicted length at which 50% of the Yelloweye Rockfish are mature is between 37.3 and 40.1, with 95% confidence.</p>
<p>The calculation of the L50L50 may be illustrated on a fitted-line plot (Figure 3) by adding the code below to the code used above to construct Figure 2.</p>
<pre><code>&gt; lines(c(0,L50),c(0.5,0.5),lty=2,lwd=2,col="red")
&gt; lines(c(L50,L50),c(-0.2,0.5),lty=2,lwd=2,col="red")</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/maturity/index_files/figure-html/LogisticFit2-1.png" class="img-fluid" alt=""></p>
<p>Figure 3: Fitted logistic regression for the proportion of female Yelloweye Rockfish that are mature by total length with L50L50 shown.</p>
<p>&nbsp; &nbsp;</p>
</section>
</section>
<section id="modeling-with-summarized-data" class="level2" data-number="F.3">
<h2 data-number="F.3" class="anchored" data-anchor-id="modeling-with-summarized-data"><span class="header-section-number">F.3</span> <strong>Modeling with Summarized Data</strong></h2>
<p>Sometimes maturity data is presented in summarized format – that is, the proportion of fish for each length that were mature. Such data can be computed from the original data.frame with the code below. Note that there are two “tricks” in this code. First, the <code>maturity</code> factor variable is coerced to be a numeric variable, but 1 is subtracted from this result because values of 1 for immature and 2 for mature are returned by <code>as.numeric()</code> when applied to a factor variable. Second, the mean of this result is the proportion of ones in the data, which is the proportion of mature fish.</p>
<pre><code>&gt; df2 &lt;- df %&gt;%
    group_by(length) %&gt;%
    summarize(pmat=mean(as.numeric(maturity)-1),
              n=n()) %&gt;%
    as.data.frame()
&gt; headtail(df2)

   length pmat n
1      31    0 1
2      32    0 4
3      33    0 2
33     67    1 1
34     68    1 1
35     70    1 1</code></pre>
<p>Also note that this code is only used here to produce data to illustrate how to analyze summarized data. If one has raw data, as in this supplement, then the methods of the previous section should be used, though the technique used here provides identical answers.</p>
<p>The appropriate logistic regression model is again fit with <code>glm()</code>. However, the left side of the formula is the proportion of “successes” variable and <code>weights=</code> is set equal to the sample size used to compute each proportion. Once the model is fit, the same extractor functions can be used to summarize the results. [<em>Note that <code>glm()</code> and <code>bootCase()</code> will return a warning about non-integer number of successes when used in this way.</em>]</p>
<pre><code>&gt; glm2 &lt;- glm(pmat~length,data=df2,family=binomial,weights=n)
&gt; bcL2 &lt;- bootCase(glm2,B=1000)
&gt; cbind(Ests=coef(glm2),confint(bcL2))

                   Ests     95% LCI     95% UCI
(Intercept) -16.9482593 -28.2429637 -12.1861359
length        0.4371786   0.3175022   0.7179604

&gt; predict(glm2,data.frame(length=c(32,42)),type="response")

        1         2 
0.0493342 0.8042766 

&gt; p32a &lt;- apply(bcL2,1,predP,x=32)
&gt; quantile(p32a,c(0.025,0.975))

       2.5%       97.5% 
0.005604308 0.126490127 </code></pre>
<p>Note that the coefficients and predictions computed here are the same as in the results from using the raw data. The bootstrapped confidence intervals differ slightly due to the inherent randomization used in bootstrap resampling (and because a small number of bootstrap samples were used to produce this supplement).</p>
<p>&nbsp; &nbsp;</p>
</section>
<section id="comparing-logistic-regressions-between-groups" class="level2" data-number="F.4">
<h2 data-number="F.4" class="anchored" data-anchor-id="comparing-logistic-regressions-between-groups"><span class="header-section-number">F.4</span> <strong>Comparing Logistic Regressions Between Groups</strong></h2>
<section id="model-fitting" class="level3" data-number="F.4.1">
<h3 data-number="F.4.1" class="anchored" data-anchor-id="model-fitting"><span class="header-section-number">F.4.1</span> <strong>Model Fitting</strong></h3>
<p>It may be important to determine if the fit of the logistic regression differs between two groups. For example, one may need to determine if the logistic regression parameters differ significantly between fish captured “pre-2002” and those captured in “2002 and after” (recall that these two “eras” are recorded in <code>era</code> in <code>df</code>).</p>
<p>The model required to answer this type of question is a logistic regression version of the dummy variable regression introduced in Chapter 7 of the <strong>IFAR</strong> book. Specifically, the right side of the formula in <code>glm()</code> is modified to be <code>quant*factor</code> where <code>quant</code> is the covariate (usually length or age) and <code>factor</code> is the factor variable that identifies the groups being compared. As noted in Chapter 7 of the <strong>IFAR</strong> book, this formula is actually shorthand for a model with three terms – <code>quant</code> and <code>factor</code> main effects and the interaction between the <code>quant</code> and <code>factor</code> variables. In this case, the model is fit as shown below.</p>
<pre><code>&gt; glm3 &lt;- glm(maturity~length*era,data=df,family=binomial)</code></pre>
<p>The significance of terms in a general linear model are computed with a chi-square distribution and summarized in an “Analysis of Deviance Table”, rather than with an F distribution and ANOVA table as with a linear model. Fortunately, the Analysis of Deviance table using Type II tests is also retrieved with <code>Anova()</code> from <code>car</code>.</p>
<pre><code>&gt; Anova(glm3)

Analysis of Deviance Table (Type II tests)

Response: maturity
           LR Chisq Df Pr(&gt;Chisq)
length       68.599  1    &lt; 2e-16
era           0.005  1    0.94541
length:era    3.100  1    0.07831</code></pre>
<p>As with the ANOVA table in a dummy variable regression, the Analysis of Deviance table should be read from the bottom. In this case, the interaction term is not signficant which suggests that the slopes for the logit-transformed models do not differ between the eras. The <code>era</code> main effect is also not signficant, which suggests that the y-intercepts for the logit-transformed models do not differ between the eras. Thus, there is no signficant difference in the logistic regressions between fish captured in the two eras.</p>
</section>
<section id="comparing-lengths--or-ages-at-maturity" class="level3" data-number="F.4.2">
<h3 data-number="F.4.2" class="anchored" data-anchor-id="comparing-lengths--or-ages-at-maturity"><span class="header-section-number">F.4.2</span> <strong>Comparing Lengths- or Ages-at-Maturity</strong></h3>
<p>A p-value for testing whether the L50L50 differed between groups may be computed from the bootstrapped samples. However, this calculation requires several steps and a good understanding of the parameter estimates from the logistic regression model fit to both groups. Thus, the steps and the parameter estimates are described further below.</p>
<p>Before building the hypothesis test, lets examine the parameter estimates for the logistic regression model.</p>
<pre><code>&gt; coef(glm3)

             (Intercept)                   length        era2002 and after 
             -27.1314345                0.6956840               14.0137840 
length:era2002 and after 
              -0.3510082 </code></pre>
<p>Note that the parameter estimates under the <code>(Intercept)</code> and <code>length</code> headings are the intercept and slope, respectively, for the “reference” group in the model. The reference group is the alphabetically first group, unless the levels of the factor variable were changed by the user as was done in this supplement. The order of the levels can be observed with <code>str()</code> or <code>levels()</code>.</p>
<pre><code>&gt; levels(df$era)

[1] "pre-2002"       "2002 and after"</code></pre>
<p>Thus, the estimated intercept and slope of the logistic regression for the “pre-2002” era fish are -27.131 and 0.696, respectively.</p>
<p>The parameter estimates under the <code>era2002 and after</code> and <code>length:era2002 and after</code> are the <strong>differences</strong> in intercept and slope between the two eras. Thus, these values need to be added to the intercept and slope for the “pre-2000” era to estimate the intercept and slope for the “2002 and after” era. Thus, the estimated intercept and slope of the logistic regression for the “2002 and after” era fish are -13.118 and 0.345, respectively.</p>
<p>The first step in building the hypothesis test for whether L50L50 differs between eras is to construct the bootstrap samples from the <code>glm()</code> object.</p>
<pre><code>&gt; bcL3 &lt;- bootCase(glm3,B=1000)  
&gt; headtail(bcL3)

        (Intercept)     length era2002 and after length:era2002 and after
[1,]      -28.66650  0.7480834         17.630834              -0.44741290
[2,]      -22.01427  0.5610905         -1.315964               0.05293831
[3,]      -29.11699  0.7535871         17.701264              -0.46385684
[998,]    -52.92599  1.2978597         43.104623              -1.04921293
[999,]    -22.29335  0.5727242         11.420617              -0.27867057
[1000,]  -610.63332 14.9158441        596.471707             -14.53849292</code></pre>
<p>The L50L50 for fish from the “pre-2002” era is computed for each sample using only the first two columns of the bootstrap sample results (i.e., the intercept and slope for the “pre-2002” era) and the <code>lrperc()</code> function created and used in a previous section. The L50L50 for fish from the “2002 and after” era is computed similarly but the last two columns in the bootstrap sample results must be added to the first two columns (i.e., produce the intercept and slope for the “2002 and after” era).</p>
<pre><code>&gt; L50.pre= apply(bcL3[,1:2],1,lrPerc,p=0.5)
&gt; L50.post=apply(bcL3[,1:2]+bcL3[,3:4],1,lrPerc,p=0.5)</code></pre>
<p>If there was no difference in L50L50 between the two eras, then one would expect the means of these two groups to be the same or, equivalently, the mean of the differences in these two value to equal zero. The difference in L50L50 for each bootstrap sample is computed below.</p>
<pre><code>&gt; L50.diff &lt;- L50.pre-L50.post</code></pre>
<p>A two-sided p-value may be computed as two times the smaller of the proportions of samples that are less than or greater than 0. [Note that the code below exploits the fact that R will treat a <code>TRUE</code> as a <code>1</code> and a <code>FALSE</code> as a <code>0</code> such that the mean of a vector of <code>TRUE</code>s and <code>FALSE</code>s will return the proportion of <code>TRUE</code>s.]</p>
<pre><code>&gt; ( p.L50.diff &lt;- 2*min(c(mean(L50.diff&gt;0),mean(L50.diff&lt;0))) )

[1] 0.556</code></pre>
<p>This result suggests that there is no significant difference in the L50L50 for fish captured in the two eras (not surprising given that the logistic regression parameters did not differ between eras).</p>
<p>Confidence intervals for the difference in L50L50 between the eras and the L50L50 for each era may be computed as before but making sure to use the correct vector of results.</p>
<pre><code>&gt; ( ci.L50.diff &lt;- quantile(L50.diff,c(0.025,0.975)) )

     2.5%     97.5% 
-1.953197  4.214636 

&gt; ( ci.L50.pre &lt;-  quantile(L50.pre,c(0.025,0.975)) )

    2.5%    97.5% 
37.24793 40.91101 

&gt; ( ci.L50.post &lt;- quantile(L50.post,c(0.025,0.975)) )

    2.5%    97.5% 
34.97016 40.16213 </code></pre>
<p>&nbsp; &nbsp;</p>
</section>
<section id="a-summary-plot-1" class="level3" data-number="F.4.3">
<h3 data-number="F.4.3" class="anchored" data-anchor-id="a-summary-plot-1"><span class="header-section-number">F.4.3</span> <strong>A Summary Plot</strong></h3>
<p>The construction of a plot that illustrates the fitted logistic regression lines for both groups is left largely as an exercise for the reader. Note that the code below uses several of the same ideas shown previously and relies on directions given in Chapter 3 of the <strong>IFAR</strong> book.</p>
<pre><code>&gt; ## Set-up colors
&gt; clrs1 &lt;- c("black","red")
&gt; clrs2 &lt;- col2rgbt(clrs1,1/5)
&gt; ## Get predicted values for each era
&gt; lvls &lt;- levels(df$era)
&gt; lens &lt;- seq(30,70,length.out=99)
&gt; pa02 &lt;- predict(glm3,type="response",
                  data.frame(length=lens,era=factor("2002 and after",levels=lvls)))
&gt; pp02 &lt;- predict(glm3,type="response",
                  data.frame(length=lens,era=factor("pre-2002",levels=lvls)))
&gt; ## Make the base plot
&gt; plot((as.numeric(maturity)-1)~length,data=filterD(df,era==lvls[1]),
       pch=19,col=clrs2[1],xlab="Total Length (cm)",ylab="Proportion Mature")
&gt; points((as.numeric(maturity)-1)~length,data=filterD(df,era==lvls[2]),
       pch=19,col=clrs2[2])
&gt; ## Add the two fitted lines
&gt; lines(pa02~lens,lwd=2,col=clrs1[1])
&gt; lines(pp02~lens,lwd=2,col=clrs1[2])</code></pre>
<p><img src="http://derekogle.com/IFAR/supplements/maturity/index_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" alt=""></p>
<p>Figure 4: Fitted logistic regression for the proportion of female Yelloweye Rockfish that are mature by total length separated by the “pre-2002” and “2002 and after” eras.</p>
<p>&nbsp;</p>
<hr>
</section>
</section>
<section id="reproducibility-information" class="level2" data-number="F.5">
<h2 data-number="F.5" class="anchored" data-anchor-id="reproducibility-information"><span class="header-section-number">F.5</span> <strong>Reproducibility Information</strong></h2>
<ul>
<li><p><strong>Compiled Date:</strong> Fri Nov 06 2015</p></li>
<li><p><strong>Compiled Time:</strong> 5:16:09 PM</p></li>
<li><p><strong>R Version:</strong> R version 3.2.2 (2015-08-14)</p></li>
<li><p><strong>System:</strong> Windows, i386-w64-mingw32/i386 (32-bit)</p></li>
<li><p><strong>Base Packages:</strong> base, datasets, graphics, grDevices, methods, stats, utils</p></li>
<li><p><strong>Required Packages:</strong> FSA, magrittr, dplyr, lubridate, car, captioner, knitr and their dependencies (assertthat, DBI, digest, evaluate, formatR, gdata, gplots, graphics, grDevices, highr, Hmisc, lazyeval, markdown, MASS, memoise, methods, mgcv, nnet, pbkrtest, plotrix, plyr, quantreg, R6, Rcpp, sciplot, stats, stringr, tools, utils, yaml)</p></li>
<li><p><strong>Other Packages:</strong> captioner_2.2.3, car_2.1-0, dplyr_0.4.3, extrafont_0.17, FSA_0.8.4, knitr_1.11, lubridate_1.3.3, magrittr_1.5</p></li>
<li><p><strong>Loaded-Only Packages:</strong> assertthat_0.1, DBI_0.3.1, digest_0.6.8, evaluate_0.8, extrafontdb_1.0, formatR_1.2.1, gdata_2.17.0, grid_3.2.2, gtools_3.5.0, highr_0.5.1, htmltools_0.2.6, lattice_0.20-33, lazyeval_0.1.10, lme4_1.1-10, MASS_7.3-44, Matrix_1.2-2, MatrixModels_0.4-1, memoise_0.2.1, mgcv_1.8-8, minqa_1.2.4, nlme_3.1-122, nloptr_1.0.4, nnet_7.3-11, parallel_3.2.2, pbkrtest_0.4-2, plyr_1.8.3, quantreg_5.19, R6_2.1.1, Rcpp_0.12.1, rmarkdown_0.8.1, Rttf2pt1_1.3.3, SparseM_1.7, splines_3.2.2, stringi_1.0-1, stringr_1.0.0, tools_3.2.2, yaml_2.1.13</p></li>
<li><p><strong>Links:</strong> <a href="http://derekogle.com/IFAR/supplements/maturity/maturity.R">Script</a> / <a href="http://derekogle.com/IFAR/supplements/maturity/index.Rmd">RMarkdown</a></p></li>
</ul>
<hr>
<p>&nbsp;</p>
</section>
<section id="references" class="level2" data-number="F.6">
<h2 data-number="F.6" class="anchored" data-anchor-id="references"><span class="header-section-number">F.6</span> <strong>References</strong></h2>
<p>Grolemund, G., and H. Wickham. 2011. Dates and times made easy with lubridate. Journal of Statistical Software 40(3):1–25.</p>
<p>Pope, K. L., S. E. Lochmann, and M. K. Young. 2010. Methods for assessing fish populations. Pages 325–351 <em>in</em> W. A. Hubert and M. C. Quist, editors. Inland fisheries management in north americaThird. American Fisheries Society, Bethesda, MD.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./basicstats.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title"><strong>Basic Data Manipulations</strong></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>